# Defualt config file

[general]

# required
PasswordHint = "What is your favorite color?"
# required
PasswordKey = ""
# required
MaxRetention = 10  # Max=10, Default=10

# optional
http_proxy = ""
https_proxy = ""
socks_proxy = ""
no_proxy = "localhost, 127.0.0.1"


[source.firefox]
# required
enabled = false
# required
dir = "/path/to/firefox/profile/folder/"
# required, options: hourly, daily, weekly
frequency = "daily"


[source.sensitive]
# required
enabled = false
# required
dir = "/path/to/sensitive/folder/"
# required, options: hourly, daily, weekly
frequency = "daily"


[remote.dropbox]
name = "dropbox"
enabled = false

[remote.onedrive]
name = "onedrive"
enabled = false

[remote.iclouddrive]
name = "iclouddrive"
enabled = false

[remote.sftp]
name = "sftp"
enabled = false