# Testing config file
[general]

PasswordHint = "What is your favorite color?"
PasswordKey = ""

MaxRetention = 10  # Max=10, Default=10

http_proxy = ""
https_proxy = ""
socks_proxy= ""


[source.firefox]

enabled = false
dirs = "~/.mozilla/firefox/uw2nng9t.Dev"
frequency = "daily"


[source.folder]

enabled = false
dir = "~/Documents/important/"
frequency = "hourly"


[remote.dropbox]
name = "dropbox"
enabled = false

[remote.onedrive]
name = "onedrive"
enabled = false

[remote.iclouddrive]
name = "iclouddrive"
enabled = false

[remote.sftp]
name = "sftp"
enabled = false
