# Testing config file
[general]

PasswordHint = "What is your favorite color?"
PasswordKey = ""

MaxRetention = 10  # Max=10, Default=10

http_proxy = ""
https_proxy = ""
socks_proxy= ""


[source.firefox]

enabled = false
dirs = "~/.mozilla/firefox/uw2nng9t.Dev"
frequency = "daily"


[source.folder]

enabled = false
dir = "~/Documents/important/"
frequency = "hourly"


[remote.dropbox]

enabled = false

app_key = ""
app_secret = ""

http_proxy=""
https_proxy=""
socks_proxy= ""


[remote.onedrive]

enabled = false

client_id = ""
client_secret = ""

http_proxy=""
https_proxy=""
socks_proxy= ""


[remote.icloud]

enabled = false

apple_id = ""
client_id = ""
trust_token = ""

http_proxy=""
https_proxy=""
socks_proxy= ""


[remote.sftp]

enabled = false

username = ""
ipaddr = ""
port = 20270

http_proxy=""
https_proxy=""
socks_proxy= ""
