# Defualt config file

[general]

# required
PasswordHint = "What is your favorite color?"
# required
PasswordKey = "your_password_hash_string"
# required, integar (0, 10), defaults to 10
MaxRetention = 10

# optional
http_proxy = ""
# optional
https_proxy = ""
# optional
socks_proxy = ""
# optional



[source.firefox]
# required
enabled = false
# required
dir = "/path/to/firefox/profile/folder/"
# required, options: hourly, daily, weekly
frequency = "daily"


[source.folder]
# required
enabled = false
# required
dir = "/path/to/sensitive/folder/"
# required, options: hourly, daily, weekly
frequency = "daily"


[remote.dropbox]
name = "dropbox"
enabled = false

[remote.onedrive]
name = "onedrive"
enabled = false

[remote.iclouddrive]
name = "iclouddrive"
enabled = false

[remote.sftp]
name = "sftp"
enabled = false
http_proxy = ""
# optional
https_proxy = ""
# optional
socks_proxy = ""
# optional




[remote.onedrive]
# required
enabled = false
# required
client_id = ""
# required
client_secret = ""

# optional
http_proxy = ""
# optional
https_proxy = ""
# optional
socks_proxy = ""
# optional




[remote.icloud]
# required
enabled = false
# required
apple_id = ""
# required
client_id = ""

# optional
http_proxy = ""
# optional
https_proxy = ""
# optional
socks_proxy = ""
# optional




[remote.sftp]
# required
enabled = false

# required, need setup NoPassword Login first
username = ""
# required
ipaddr = ""
# required
port = 22

# optional
http_proxy = ""
# optional
https_proxy = ""
# optional
socks_proxy = ""
# optional

